openapi: 3.0.3
info:
  title: API - Cabeleleila Leila (DSIN)
  description: API REST para gestão de agendamentos e usuários do salão.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor Java Spring Boot (Local)

paths:

  # HEALTH CHECK
  /health:
    get:
      tags:
        - Health
      summary: Check API Health
      description: Verifica se o servidor está online e pronto para receber requisições.
      operationId: checkHealth
      responses:
        '200':
          description: API is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "UP"